enum Status {
  initial,
  loading,
  loaded,
  success,
  failed,
  emailAlreadyInUse,
  weakPassword,
  invalidEmail,
  userNotFound,
  wrongPassword,
  userDisabled,
  operationNotAllowed,
  tooManyRequests,
  undefined,
}